/* shallue.cpp  author: Steven Hayman with help be Andrew Shallue
Date: summer 2011

A subset product algorithm for constructing Carmichael numbers.  
Currently this file does not have a main - instead it is part of 
the run.cpp superstructure
*/

#include <NTL/ZZ.h>
#include <NTL/quad_float.h>
#include <NTL/RR.h>
#include <iostream>
#include <fstream>
#include "ModElTime.h"
#include <vector>
#include <list>
#include <time.h>
#include <algorithm>

NTL_CLIENT

/* The primary call.  The main subroutine is phase2 */
void shallue(vector<long>& primes, vector<long>& exponents, char* infileName1, char* infileName2, char* outfileName, bool verbose);

/* LohNiebuhr is used to get b and other elements into the proper initial
subgroup */
bool LohNiebuhr(vector<long>& primes, vector<long>& exponents, ZZ& L, vector< vector<ModElTime> >& S, int j, ModElTime& b, bool dist, bool verbose);

/* b is the product of all primes modulo L.  It is a distinguished elt which 
needs to be carried along at each step */
ModElTime getb(ZZ& L, char* infileName);

/* getN estimates the number of primes generated by Lambda */
ZZ getN(vector<long>& primes, vector<long>& exponents, ZZ& L);

/* S is the collection of primes we will work with */
void getS(vector< vector<ModElTime> >& S, char* infileName, long limit, long j);

/* this is a helper function for LohNiebuhr. It simply returns true 
if there is something b can be paired with to lower its omega value */
bool nextPrime(vector<ModElTime>::iterator& it, ModElTime& b, vector< vector<ModElTime> >& S, ZZ& L);

/* this is used in standard library functions for sorting(sort) and searching
(lower_bound).  It grabs omega value of a and b (error if not the same)
and returns true if a's residue at that position is smaller */ 
bool compareResidue(ModElTime a, ModElTime b);

/* the main work of the alg: elts are paired into smaller subgroups */
bool phase2(vector<long>& primes, vector<long>& exponents, ModElTime& b, vector< list<ModElTime> >& products, ZZ& M, ZZ& L);

/* The M's are the mechanism by which we change subgroups.  As M grows, 
the subgroup shrinks and we end when M = Lambda.  WorkM is the quotient 
between M's, it is the value we zero out at the current level */
ZZ getNextM(vector<long>& primes, vector<long>& exponents, ZZ& M, quad_float& levelbits);

long getWorkM(vector<long>& primes, vector<long>& exponents, ZZ& M , ZZ& N);